//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPetProject.DomainObjects
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EPetISTEDBEntities : DbContext
    {
        public EPetISTEDBEntities()
            : base("name=EPetISTEDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<clinic> clinic { get; set; }
        public virtual DbSet<log> log { get; set; }
        public virtual DbSet<mobileuser> mobileuser { get; set; }
        public virtual DbSet<pet> pet { get; set; }
        public virtual DbSet<rehoming> rehoming { get; set; }
        public virtual DbSet<treatment> treatment { get; set; }
    }
}
