//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPetProject.DomainObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class treatment
    {
        public int Id { get; set; }
        public Nullable<int> PetId { get; set; }
        public Nullable<int> ClinicId { get; set; }
        public string Title { get; set; }
        public string Descr { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual clinic clinic { get; set; }
        public virtual pet pet { get; set; }
    }
}
